version: '3'

services:

  anaconda3:
    build:
      context: .
      dockerfile: anaconda3/Dockerfile
    container_name: donorschoose_anaconda3
    env_file:
    - .env
    ports:
      - "8888:8888"
    volumes:
      - "$DATADIR:/data"
      - "$NOTEBOOKSDIR:/notebooks"
